/**
  ******************************************************************************
  * @file    LED_Matrix_Driver.c
  * @brief   LED矩阵驱动源文件
  * @author  Generated by Lingma
  * @date    2026-05-03
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "LED_Matrix_Driver.h"
#include "stm32h7xx.h"

/* 私有变量 ---------------------------------------------------------*/
// 帧缓冲区存储空间（额外31字节用于内存对齐）
static uint8_t g_tim3_frame_storage[LED_FRAME_CACHE_BYTES + 31U];
static uint8_t g_tim8_frame_storage[LED_FRAME_CACHE_BYTES + 31U];

// 指向对齐后帧缓冲区的指针
static uint16_t *g_tim3_frame = (uint16_t *)0;  // TIM3使用的帧缓冲区指针（控制GPIOD）
static uint16_t *g_tim8_frame = (uint16_t *)0;  // TIM8使用的帧缓冲区指针（控制GPIOE）

// LED颜色数据存储数组 [灯带索引][LED索引] = GRB颜色值
static uint32_t g_led_grb[LED_CHAIN_COUNT][LEDS_PER_CHAIN];

// 状态标志变量
static volatile uint8_t g_frame_busy = 0U;      // 帧传输忙标志（1=正在传输，0=空闲）
static volatile uint8_t g_tim3_done = 0U;       // TIM3 DMA传输完成标志
static volatile uint8_t g_tim8_done = 0U;       // TIM8 DMA传输完成标志

// 外部声明的DMA句柄（在dma.c中定义）
extern DMA_HandleTypeDef hdma_tim3_up;
extern DMA_HandleTypeDef hdma_tim8_up;

/* 私有函数实现 -----------------------------------------------------*/

/**
  * @brief  初始化帧缓冲区指针（32字节对齐）
  * @retval None
  * 
  * 由于DMA传输可能需要内存对齐，此函数确保帧缓冲区指针
  * 指向32字节对齐的地址，以提高DMA传输效率。
  */
static void LED_InitFrameBuffers(void)
{
  uintptr_t tim3_base;  // TIM3缓冲区基地址
  uintptr_t tim8_base;  // TIM8缓冲区基地址

  // 获取原始存储空间的地址
  tim3_base = (uintptr_t)g_tim3_frame_storage;
  tim8_base = (uintptr_t)g_tim8_frame_storage;
  
  // 进行32字节对齐（向上取整到最近的32字节边界）
  tim3_base = (tim3_base + 31U) & ~(uintptr_t)31U;
  tim8_base = (tim8_base + 31U) & ~(uintptr_t)31U;

  // 设置对齐后的帧缓冲区指针
  g_tim3_frame = (uint16_t *)tim3_base;
  g_tim8_frame = (uint16_t *)tim8_base;
}

/**
  * @brief  构建LED帧数据
  * @retval None
  * 
  * 此函数将g_led_grb数组中的颜色数据转换为时序波形，
  * 存储到TIM3和TIM8的帧缓冲区中，用于DMA传输到GPIO。
  * 
  * WS2812B协议时序：
  * - T0H: 0码高电平时间 ~350ns
  * - T0L: 0码低电平时间 ~900ns  
  * - T1H: 1码高电平时间 ~900ns
  * - T1L: 1码低电平时间 ~350ns
  * - 复位时间: >280us低电平
  * 
  * 本实现使用4个时隙表示1位数据：
  * 时隙0: 高电平（T0H/T1H开始）
  * 时隙1: 数据位决定（1=高，0=低）
  * 时隙2: 低电平（T0L/T1L开始）
  * 时隙3: 低电平（保持低电平）
  */
static void LED_BuildFrame(void)
{
  uint32_t slotIndex = 0U;    // 当前时隙索引
  uint32_t ledIndex;          // LED索引
  uint32_t bitIndex;          // 位索引（0-23，MSB优先）
  uint32_t chainIndex;        // 灯带索引

  // 遍历每个LED（从0到15）
  for (ledIndex = 0U; ledIndex < LEDS_PER_CHAIN; ledIndex++)
  {
    // 遍历每个像素的24位数据（GRB格式，高位在前）
    for (bitIndex = 0U; bitIndex < LED_BITS_PER_PIXEL; bitIndex++)
    {
      uint16_t portD = 0xFFFFU;  // GPIOD输出值（初始全高）
      uint16_t portE = 0xFFFFU;  // GPIOE输出值（初始全高）

      // 时隙0: 所有LED输出高电平（开始T0H/T1H）
      g_tim3_frame[slotIndex] = portD;
      g_tim8_frame[slotIndex] = portE;
      slotIndex++;

      // 准备时隙1的数据（根据实际数据位决定高低电平）
      portD = 0U;  // 初始全低
      portE = 0U;  // 初始全低

      // 遍历所有32条灯带
      for (chainIndex = 0U; chainIndex < LED_CHAIN_COUNT; chainIndex++)
      {
        // 获取当前LED的颜色值
        uint32_t v = g_led_grb[chainIndex][ledIndex];
        // 分离GRB分量
        uint8_t g = (uint8_t)((v >> 16U) & 0xFFU);  // Green分量
        uint8_t r = (uint8_t)((v >> 8U) & 0xFFU);   // Red分量
        uint8_t b = (uint8_t)(v & 0xFFU);           // Blue分量

        /* 应用全局亮度缩放（右移 LED_BRIGHTNESS_SHIFT 位） */
        g = (uint8_t)(g >> LED_BRIGHTNESS_SHIFT);
        r = (uint8_t)(r >> LED_BRIGHTNESS_SHIFT);
        b = (uint8_t)(b >> LED_BRIGHTNESS_SHIFT);

        // 重新组合缩放后的颜色值
        uint32_t scaled = ((uint32_t)g << 16U) | ((uint32_t)r << 8U) | (uint32_t)b;

        // 检查当前位是否为1（从最高位开始，位23到位0）
        if ((scaled & (1UL << (23U - bitIndex))) != 0UL)
        {
          // 如果是1，则对应GPIO输出高电平
          if (chainIndex < 16U)
          {
            // 灯带0-15连接到GPIOD[0-15]
            portD |= (uint16_t)(1U << chainIndex);
          }
          else
          {
            // 灯带16-31连接到GPIOE[0-15]
            portE |= (uint16_t)(1U << (chainIndex - 16U));
          }
        }
        // 如果是0，则保持低电平（已在上面初始化为0）
      }

      // 时隙1: 输出实际数据位（1=高，0=低）
      g_tim3_frame[slotIndex] = portD;
      g_tim8_frame[slotIndex] = portE;
      slotIndex++;

      // 时隙2: 所有LED输出低电平（开始T0L/T1L）
      g_tim3_frame[slotIndex] = 0U;
      g_tim8_frame[slotIndex] = 0U;
      slotIndex++;

      // 时隙3: 继续保持低电平
      g_tim3_frame[slotIndex] = 0U;
      g_tim8_frame[slotIndex] = 0U;
      slotIndex++;
    }
  }

  // 填充剩余的时隙为低电平（复位时序）
  while (slotIndex < LED_FRAME_SLOTS)
  {
    g_tim3_frame[slotIndex] = 0U;
    g_tim8_frame[slotIndex] = 0U;
    slotIndex++;
  }
}

/**
  * @brief  清理帧缓存（预留函数，当前为空实现）
  * @retval None
  * 
  * 此函数可用于清理CPU缓存，确保DMA看到最新的数据。
  * 在当前实现中为空，因为STM32H7的缓存配置可能不需要。
  */
static void LED_CleanFrameCache(void)
{
}

/**
  * @brief  停止当前帧传输
  * @retval None
  * 
  * 停止定时器和DMA传输，并重置GPIO输出和状态标志。
  */
static void LED_StopFrame(void)
{
  // 停止定时器
  (void)HAL_TIM_Base_Stop(&htim3);
  (void)HAL_TIM_Base_Stop(&htim8);
  
  // 禁用DMA请求
  __HAL_TIM_DISABLE_DMA(&htim3, TIM_DMA_UPDATE);
  __HAL_TIM_DISABLE_DMA(&htim8, TIM_DMA_UPDATE);
  
  // 将GPIO输出设为低电平（安全状态）
  GPIOD->ODR = 0U;
  GPIOE->ODR = 0U;
  
  // 清除忙标志
  g_frame_busy = 0U;
}

/* 公共函数实现 -----------------------------------------------------*/

/**
  * @brief  初始化LED矩阵驱动
  * @retval None
  */
void LED_Matrix_Init(void)
{
  // 初始化帧缓冲区指针
  LED_InitFrameBuffers();
  
  // 清空所有LED数据
  LED_Matrix_ClearAll();
}

/**
  * @brief  启动新的帧传输
  * @retval None
  * 
  * 此函数负责启动完整的LED帧刷新过程：
  * 1. 检查是否已有传输进行中
  * 2. 初始化帧缓冲区（如果需要）
  * 3. 构建帧数据
  * 4. 配置并启动DMA传输
  * 5. 启动定时器
  */
void LED_Matrix_StartFrame(void)
{
  // 如果当前帧传输正在进行中，直接返回（避免重入）
  if (g_frame_busy != 0U)
  {
    return;
  }

  // 如果帧缓冲区指针未初始化，进行初始化
  if ((g_tim3_frame == (uint16_t *)0) || (g_tim8_frame == (uint16_t *)0))
  {
    LED_InitFrameBuffers();
  }

  // 设置忙标志和完成标志
  g_frame_busy = 1U;
  g_tim3_done = 0U;
  g_tim8_done = 0U;

  // 构建帧数据
  LED_BuildFrame();
  // 清理缓存（预留）
  LED_CleanFrameCache();

  // 禁用DMA，重置定时器计数器，清除更新标志
  __HAL_TIM_DISABLE_DMA(&htim3, TIM_DMA_UPDATE);
  __HAL_TIM_DISABLE_DMA(&htim8, TIM_DMA_UPDATE);
  __HAL_TIM_SET_COUNTER(&htim3, 0U);
  __HAL_TIM_SET_COUNTER(&htim8, 0U);
  __HAL_TIM_CLEAR_FLAG(&htim3, TIM_FLAG_UPDATE);
  __HAL_TIM_CLEAR_FLAG(&htim8, TIM_FLAG_UPDATE);

  // 启动TIM3的DMA传输：从帧缓冲区到GPIOD->ODR
  if (HAL_DMA_Start_IT(&hdma_tim3_up, (uint32_t)g_tim3_frame, (uint32_t)&GPIOD->ODR, LED_FRAME_SLOTS) != HAL_OK)
  {
    Error_Handler();
  }

  // 启动TIM8的DMA传输：从帧缓冲区到GPIOE->ODR
  if (HAL_DMA_Start_IT(&hdma_tim8_up, (uint32_t)g_tim8_frame, (uint32_t)&GPIOE->ODR, LED_FRAME_SLOTS) != HAL_OK)
  {
    Error_Handler();
  }

  // 使能定时器的DMA请求
  __HAL_TIM_ENABLE_DMA(&htim3, TIM_DMA_UPDATE);
  __HAL_TIM_ENABLE_DMA(&htim8, TIM_DMA_UPDATE);

  // 启动定时器
  if (HAL_TIM_Base_Start(&htim3) != HAL_OK)
  {
    Error_Handler();
  }

  if (HAL_TIM_Base_Start(&htim8) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief  停止帧传输（公共接口）
  * @retval None
  */
void LED_Matrix_StopFrame(void)
{
  LED_StopFrame();
}

/**
  * @brief  检查帧传输是否忙碌
  * @retval uint8_t: 1=忙碌, 0=空闲
  */
uint8_t LED_Matrix_IsFrameBusy(void)
{
  return g_frame_busy;
}

/**
  * @brief  设置指定LED的颜色
  * @param  chain: 灯带索引 (0-31)
  * @param  led: LED索引 (0-15)
  * @param  grb_color: GRB颜色值
  * @retval None
  */
void LED_Matrix_SetPixel(uint32_t chain, uint32_t led, uint32_t grb_color)
{
  if (chain < LED_CHAIN_COUNT && led < LEDS_PER_CHAIN)
  {
    g_led_grb[chain][led] = grb_color;
  }
}

/**
  * @brief  获取指定LED的颜色
  * @param  chain: 灯带索引 (0-31)
  * @param  led: LED索引 (0-15)
  * @retval uint32_t: GRB颜色值
  */
uint32_t LED_Matrix_GetPixel(uint32_t chain, uint32_t led)
{
  if (chain < LED_CHAIN_COUNT && led < LEDS_PER_CHAIN)
  {
    return g_led_grb[chain][led];
  }
  return 0;
}

/**
  * @brief  清空所有LED
  * @retval None
  */
void LED_Matrix_ClearAll(void)
{
  for (uint32_t chain = 0; chain < LED_CHAIN_COUNT; chain++)
  {
    for (uint32_t led = 0; led < LEDS_PER_CHAIN; led++)
    {
      g_led_grb[chain][led] = 0;
    }
  }
}

/* DMA回调函数实现 --------------------------------------------------*/

/**
  * @brief  TIM3 DMA传输完成回调函数
  * @param  hdma: DMA句柄指针
  * @retval None
  * 
  * 当TIM3的DMA传输完成后调用此函数。
  * 只有当TIM8也完成时，才停止整个帧传输。
  */
void LED_Matrix_OnTim3DmaComplete(DMA_HandleTypeDef *hdma)
{
  (void)hdma;  // 避免编译器警告
  g_tim3_done = 1U;  // 标记TIM3完成
  
  // 检查TIM8是否也已完成
  if (g_tim8_done != 0U)
  {
    // 两个DMA都完成，停止帧传输
    LED_StopFrame();
  }
}

/**
  * @brief  TIM8 DMA传输完成回调函数
  * @param  hdma: DMA句柄指针
  * @retval None
  * 
  * 当TIM8的DMA传输完成后调用此函数。
  * 只有当TIM3也完成时，才停止整个帧传输。
  */
void LED_Matrix_OnTim8DmaComplete(DMA_HandleTypeDef *hdma)
{
  (void)hdma;  // 避免编译器警告
  g_tim8_done = 1U;  // 标记TIM8完成
  
  // 检查TIM3是否也已完成
  if (g_tim3_done != 0U)
  {
    // 两个DMA都完成，停止帧传输
    LED_StopFrame();
  }
}

/**
  * @brief  DMA传输错误回调函数
  * @param  hdma: DMA句柄指针
  * @retval None
  * 
  * 当DMA传输发生错误时调用此函数，进入错误处理。
  */
void LED_Matrix_OnDmaError(DMA_HandleTypeDef *hdma)
{
  (void)hdma;  // 避免编译器警告
  Error_Handler();  // 调用全局错误处理函数
}