/**
  ******************************************************************************
  * @file    LED_Matrix_Driver.h
  * @brief   LED矩阵驱动头文件
  * @author  Generated by Lingma
  * @date    2026-05-03
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

#ifndef LED_MATRIX_DRIVER_H
#define LED_MATRIX_DRIVER_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "dma.h"
#include "tim.h"
#include "gpio.h"

/* LED矩阵配置参数 */
#define LED_CHAIN_COUNT              32U        /*!< LED灯带数量：32条 */
#define LEDS_PER_CHAIN               16U        /*!< 每条灯带的LED数量：16个 */
#define LED_BITS_PER_PIXEL           24U        /*!< 每个像素的位数：24位（GRB格式，每通道8位） */
#define LED_SLOTS_PER_BIT            4U         /*!< 每个数据位使用的时隙数量：4个 */
#define LED_RESET_TIME_US            280U       /*!< LED复位时间：280微秒 */
#define LED_SLOT_TIME_NS             312U       /*!< 每个时隙的时间：312纳秒 */
#define LED_BRIGHTNESS_SHIFT         3U         /*!< 亮度缩放因子：右移3位相当于亮度降为1/8（0=全亮,1=1/2,2=1/4,3=1/8） */

/* 计算帧缓冲区大小 */
#define LED_RESET_SLOTS              ((LED_RESET_TIME_US * 1000U + LED_SLOT_TIME_NS - 1U) / LED_SLOT_TIME_NS)  /*!< 复位时隙数量 */
#define LED_FRAME_SLOTS              ((LEDS_PER_CHAIN * LED_BITS_PER_PIXEL * LED_SLOTS_PER_BIT) + LED_RESET_SLOTS)  /*!< 总帧时隙数量 */
#define LED_FRAME_BYTES              (LED_FRAME_SLOTS * sizeof(uint16_t))  /*!< 帧缓冲区字节数 */
#define LED_FRAME_CACHE_BYTES        ((LED_FRAME_BYTES + 31U) & ~31U)      /*!< 缓存对齐后的字节数（32字节对齐） */

/* 函数声明 */
void LED_Matrix_Init(void);
void LED_Matrix_StartFrame(void);
void LED_Matrix_StopFrame(void);
uint8_t LED_Matrix_IsFrameBusy(void);
void LED_Matrix_SetPixel(uint32_t chain, uint32_t led, uint32_t grb_color);
uint32_t LED_Matrix_GetPixel(uint32_t chain, uint32_t led);
void LED_Matrix_ClearAll(void);

/* 私有函数声明（仅供内部使用） */
void LED_Matrix_OnTim3DmaComplete(DMA_HandleTypeDef *hdma);
void LED_Matrix_OnTim8DmaComplete(DMA_HandleTypeDef *hdma);
void LED_Matrix_OnDmaError(DMA_HandleTypeDef *hdma);

#ifdef __cplusplus
}
#endif

#endif /* LED_MATRIX_DRIVER_H */